<a href="https://colab.research.google.com/github/ivanvzqzz/programacionMCD/blob/main/analizando-conjunto-pd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
import requests

url = "http://www.dgis.salud.gob.mx/descargas/datosabiertos/nacimientos/sinac_2023.zip?V=2024.05.14"
response = requests.get(url)
with open("sinac_2023.zip", "wb") as f:
    f.write(response.content)

In [3]:
import zipfile

with zipfile.ZipFile("sinac_2023.zip", "r") as zip_ref:
    zip_ref.extractall("sinac_2023")

In [6]:
df = pd.read_csv("sinac_2023/Nacimientos_2023.csv")
df

,NACIOEXTRANJERO,ENTIDADNACIMIENTO,MUNICIPIONACIMIENTO,EDAD,SECONSIDERAINDIGENA,HABLALENGUAINDIGENA,FECHANACIMIENTOMADRE,ESTADOCONYUGAL,RESIDEEXTRANJERO,ENTIDADRESIDENCIA,...,TIPOMEDICOATENDIO,ENTIDADFEDERATIVAPARTO,MUNICIPIOPARTO,LOCALIDADPARTO,CERTIFICADOPOR,CLUESCERTIFICA,ENTIDADFEDERATIVACERTIFICA,MUNICIPIOCERTIFICA,LOCALIDADCERTIFICA,FECHACERTIFICADO
0,2,9,12,25,2,2,23/07/1997,5,2,9,...,11.0,9,10,1,1,NaN,9,10,1,09/05/2023
1,2,15,33,22,2,2,11/05/2000,5,2,9,...,11.0,9,5,1,1,NaN,9,5,1,28/02/2023
2,2,12,28,20,1,1,12/08/2002,4,2,12,...,14.0,12,28,1,2,NaN,12,28,1,17/06/2023
3,2,13,63,28,2,2,24/12/1994,4,2,13,...,11.0,13,63,1,1,NaN,13,63,1,21/11/2023
4,2,15,101,29,2,2,23/05/1993,4,2,15,...,11.0,15,54,35,1,NaN,15,54,35,08/05/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521275,2,9,15,23,2,2,18/12/1999,4,2,9,...,11.0,9,15,1,2,DFSSA003973,9,15,1,20/11/2023
1521276,2,15,40,16,2,2,11/02/2007,4,2,15,...,11.0,15,40,13,2,MCSSA010251,15,40,13,15/08/2023
1521277,2,8,19,21,2,2,06/07/2002,1,2,8,...,11.0,8,19,1,2,CHSMP000066,8,19,1,27/11/2023
1521278,2,14,114,36,2,2,11/08/1987,5,2,25,...,11.0,25,1,1,7,SLSSA000024,25,1,1,21/11/2023
1521279,2,11,30,40,2,2,05/12/1982,4,2,11,...,11.0,11,14,1,1,GTSSA001290,11,14,1,30/09/2023

In [13]:
print(df.dtypes)

NACIOEXTRANJERO                int64
ENTIDADNACIMIENTO              int64
MUNICIPIONACIMIENTO            int64
EDAD                           int64
SECONSIDERAINDIGENA            int64
                               ...
CLUESCERTIFICA                object
ENTIDADFEDERATIVACERTIFICA     int64
MUNICIPIOCERTIFICA             int64
LOCALIDADCERTIFICA             int64
FECHACERTIFICADO              object
Length: 64, dtype: object

Este dataframe es un ejemplo de como algunas veces los datos capturados no tienen la forma bonita que deseamos o que estamos acostumbrados, ya que casi todas las columnas son del tipo `int64`. Aún así, veamos qué significa cada una de ellas.

In [21]:
df.NACIOEXTRANJERO.unique()

array([2, 1])

Notamos primero que la columna `NACIOEXTRANJERO` toma valores 1 o 2, entonces haciendo la prueba, vemos que el 2 corresponde a nacimiento nacional y 1 corresponde a nacimiento en el extranjero.

In [33]:
df_nacionales = df[df.NACIOEXTRANJERO == 2]
df_nacionales

,NACIOEXTRANJERO,ENTIDADNACIMIENTO,MUNICIPIONACIMIENTO,EDAD,SECONSIDERAINDIGENA,HABLALENGUAINDIGENA,FECHANACIMIENTOMADRE,ESTADOCONYUGAL,RESIDEEXTRANJERO,ENTIDADRESIDENCIA,...,TIPOMEDICOATENDIO,ENTIDADFEDERATIVAPARTO,MUNICIPIOPARTO,LOCALIDADPARTO,CERTIFICADOPOR,CLUESCERTIFICA,ENTIDADFEDERATIVACERTIFICA,MUNICIPIOCERTIFICA,LOCALIDADCERTIFICA,FECHACERTIFICADO
0,2,9,12,25,2,2,23/07/1997,5,2,9,...,11.0,9,10,1,1,NaN,9,10,1,09/05/2023
1,2,15,33,22,2,2,11/05/2000,5,2,9,...,11.0,9,5,1,1,NaN,9,5,1,28/02/2023
2,2,12,28,20,1,1,12/08/2002,4,2,12,...,14.0,12,28,1,2,NaN,12,28,1,17/06/2023
3,2,13,63,28,2,2,24/12/1994,4,2,13,...,11.0,13,63,1,1,NaN,13,63,1,21/11/2023
4,2,15,101,29,2,2,23/05/1993,4,2,15,...,11.0,15,54,35,1,NaN,15,54,35,08/05/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521275,2,9,15,23,2,2,18/12/1999,4,2,9,...,11.0,9,15,1,2,DFSSA003973,9,15,1,20/11/2023
1521276,2,15,40,16,2,2,11/02/2007,4,2,15,...,11.0,15,40,13,2,MCSSA010251,15,40,13,15/08/2023
1521277,2,8,19,21,2,2,06/07/2002,1,2,8,...,11.0,8,19,1,2,CHSMP000066,8,19,1,27/11/2023
1521278,2,14,114,36,2,2,11/08/1987,5,2,25,...,11.0,25,1,1,7,SLSSA000024,25,1,1,21/11/2023
1521279,2,11,30,40,2,2,05/12/1982,4,2,11,...,11.0,11,14,1,1,GTSSA001290,11,14,1,30/09/2023

In [38]:
df_nacionales.ENTIDADNACIMIENTO.unique()

array([ 9, 15, 12, 13, 11, 20, 14, 30,  7, 18, 21, 28, 19, 31, 26, 24, 16,
       27,  3, 23, 32, 22,  5, 10, 17,  8, 25, 29,  2,  4,  0,  1,  6, 88,
       99])

Aquí notamos un error, México solo tiene 32 entidades federativas, entonces algo raro hay aquí. Contemos las ocurrencias en cada entidad.

In [39]:
df_nacionales.ENTIDADNACIMIENTO.value_counts()

ENTIDADNACIMIENTO
15    150910
9     109739
30    106345
14    101566
21     97123
7      86777
11     81063
16     70084
20     61810
12     59802
19     54286
24     41353
8      41022
25     39724
5      39559
28     38672
27     36543
13     33846
26     30994
10     26888
31     24757
2      24609
22     23399
32     22485
17     20327
1      17513
29     16568
18     14611
23     11406
4      10680
6       7429
3       5639
0        396
88        29
99        12
Name: count, dtype: int64

Los valores de la cola contienen muy pocos datos, por lo que lo más probable es que no hayan sido correctamente capturados. Así, vamos a eliminarlos de nuestro dataframe.

In [40]:
entidades_no_validas = [0, 88, 99]
df = df_nacionales[~df_nacionales.ENTIDADNACIMIENTO.isin(entidades_no_validas)]
df

,NACIOEXTRANJERO,ENTIDADNACIMIENTO,MUNICIPIONACIMIENTO,EDAD,SECONSIDERAINDIGENA,HABLALENGUAINDIGENA,FECHANACIMIENTOMADRE,ESTADOCONYUGAL,RESIDEEXTRANJERO,ENTIDADRESIDENCIA,...,TIPOMEDICOATENDIO,ENTIDADFEDERATIVAPARTO,MUNICIPIOPARTO,LOCALIDADPARTO,CERTIFICADOPOR,CLUESCERTIFICA,ENTIDADFEDERATIVACERTIFICA,MUNICIPIOCERTIFICA,LOCALIDADCERTIFICA,FECHACERTIFICADO
0,2,9,12,25,2,2,23/07/1997,5,2,9,...,11.0,9,10,1,1,NaN,9,10,1,09/05/2023
1,2,15,33,22,2,2,11/05/2000,5,2,9,...,11.0,9,5,1,1,NaN,9,5,1,28/02/2023
2,2,12,28,20,1,1,12/08/2002,4,2,12,...,14.0,12,28,1,2,NaN,12,28,1,17/06/2023
3,2,13,63,28,2,2,24/12/1994,4,2,13,...,11.0,13,63,1,1,NaN,13,63,1,21/11/2023
4,2,15,101,29,2,2,23/05/1993,4,2,15,...,11.0,15,54,35,1,NaN,15,54,35,08/05/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1521275,2,9,15,23,2,2,18/12/1999,4,2,9,...,11.0,9,15,1,2,DFSSA003973,9,15,1,20/11/2023
1521276,2,15,40,16,2,2,11/02/2007,4,2,15,...,11.0,15,40,13,2,MCSSA010251,15,40,13,15/08/2023
1521277,2,8,19,21,2,2,06/07/2002,1,2,8,...,11.0,8,19,1,2,CHSMP000066,8,19,1,27/11/2023
1521278,2,14,114,36,2,2,11/08/1987,5,2,25,...,11.0,25,1,1,7,SLSSA000024,25,1,1,21/11/2023
1521279,2,11,30,40,2,2,05/12/1982,4,2,11,...,11.0,11,14,1,1,GTSSA001290,11,14,1,30/09/2023

In [50]:
df = df.sort_values(by=['ENTIDADNACIMIENTO'])
df

,NACIOEXTRANJERO,ENTIDADNACIMIENTO,MUNICIPIONACIMIENTO,EDAD,SECONSIDERAINDIGENA,HABLALENGUAINDIGENA,FECHANACIMIENTOMADRE,ESTADOCONYUGAL,RESIDEEXTRANJERO,ENTIDADRESIDENCIA,...,TIPOMEDICOATENDIO,ENTIDADFEDERATIVAPARTO,MUNICIPIOPARTO,LOCALIDADPARTO,CERTIFICADOPOR,CLUESCERTIFICA,ENTIDADFEDERATIVACERTIFICA,MUNICIPIOCERTIFICA,LOCALIDADCERTIFICA,FECHACERTIFICADO
756895,2,1,1,23,2,2,23/03/2000,5,2,1,...,11.0,1,1,1,1,ASIMS000016,1,1,1,23/07/2023
713039,2,1,2,38,2,2,19/01/1985,5,2,1,...,11.0,1,6,1,1,ASSSA000614,1,6,1,10/04/2023
713036,2,1,1,27,2,2,23/05/1995,5,2,1,...,11.0,1,1,1,1,ASSMP000115,1,1,1,16/04/2023
713032,2,1,1,28,2,2,28/08/1994,5,2,1,...,11.0,1,1,1,1,ASSMP000103,1,1,1,26/03/2023
713047,2,1,1,16,2,2,23/07/2006,4,2,1,...,13.0,1,1,1,1,ASSSA000042,1,1,1,30/01/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697039,2,32,17,25,2,2,10/09/1997,4,2,32,...,11.0,32,17,1,2,ZSSSA012450,32,17,1,02/02/2023
66130,2,32,17,33,2,2,25/04/1989,5,2,8,...,13.0,8,37,1,1,NaN,8,37,1,24/01/2023
697001,2,32,17,29,2,2,03/09/1993,5,2,32,...,13.0,32,17,1,2,ZSSSA012450,32,17,1,09/01/2023
697149,2,32,17,14,2,2,22/04/2008,4,2,32,...,11.0,32,17,1,2,ZSSSA012450,32,17,1,16/02/2023
172472,2,32,10,21,2,2,30/08/2001,5,2,32,...,11.0,32,10,1,1,NaN,32,10,1,07/03/2023

Sonora tiene clave de entidad 26, ¿pero será esta la misma en nuestra base de datos?

In [52]:
df.ENTIDADNACIMIENTO.value_counts()

ENTIDADNACIMIENTO
15    150910
9     109739
30    106345
14    101566
21     97123
7      86777
11     81063
16     70084
20     61810
12     59802
19     54286
24     41353
8      41022
25     39724
5      39559
28     38672
27     36543
13     33846
26     30994
10     26888
31     24757
2      24609
22     23399
32     22485
17     20327
1      17513
29     16568
18     14611
23     11406
4      10680
6       7429
3       5639
Name: count, dtype: int64

Esta informacion tiene sentido, ya que de acuerdo a documentos oficiales, la Ciudad de México tiene asignado el número 15. ¿Podremos renombrarlos para trabajar de forma mas eficiente?

In [54]:
df['ENTIDADNACIMIENTO'] = df['ENTIDADNACIMIENTO'].astype(str)
df

,NACIOEXTRANJERO,ENTIDADNACIMIENTO,MUNICIPIONACIMIENTO,EDAD,SECONSIDERAINDIGENA,HABLALENGUAINDIGENA,FECHANACIMIENTOMADRE,ESTADOCONYUGAL,RESIDEEXTRANJERO,ENTIDADRESIDENCIA,...,TIPOMEDICOATENDIO,ENTIDADFEDERATIVAPARTO,MUNICIPIOPARTO,LOCALIDADPARTO,CERTIFICADOPOR,CLUESCERTIFICA,ENTIDADFEDERATIVACERTIFICA,MUNICIPIOCERTIFICA,LOCALIDADCERTIFICA,FECHACERTIFICADO
756895,2,1,1,23,2,2,23/03/2000,5,2,1,...,11.0,1,1,1,1,ASIMS000016,1,1,1,23/07/2023
713039,2,1,2,38,2,2,19/01/1985,5,2,1,...,11.0,1,6,1,1,ASSSA000614,1,6,1,10/04/2023
713036,2,1,1,27,2,2,23/05/1995,5,2,1,...,11.0,1,1,1,1,ASSMP000115,1,1,1,16/04/2023
713032,2,1,1,28,2,2,28/08/1994,5,2,1,...,11.0,1,1,1,1,ASSMP000103,1,1,1,26/03/2023
713047,2,1,1,16,2,2,23/07/2006,4,2,1,...,13.0,1,1,1,1,ASSSA000042,1,1,1,30/01/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697039,2,32,17,25,2,2,10/09/1997,4,2,32,...,11.0,32,17,1,2,ZSSSA012450,32,17,1,02/02/2023
66130,2,32,17,33,2,2,25/04/1989,5,2,8,...,13.0,8,37,1,1,NaN,8,37,1,24/01/2023
697001,2,32,17,29,2,2,03/09/1993,5,2,32,...,13.0,32,17,1,2,ZSSSA012450,32,17,1,09/01/2023
697149,2,32,17,14,2,2,22/04/2008,4,2,32,...,11.0,32,17,1,2,ZSSSA012450,32,17,1,16/02/2023
172472,2,32,10,21,2,2,30/08/2001,5,2,32,...,11.0,32,10,1,1,NaN,32,10,1,07/03/2023

In [58]:
df.loc[df['ENTIDADNACIMIENTO'] == '1', 'ENTIDADNACIMIENTO'] = 'Aguascalientes'
df.loc[df['ENTIDADNACIMIENTO'] == '2', 'ENTIDADNACIMIENTO'] = 'Baja California'
df.loc[df['ENTIDADNACIMIENTO'] == '3', 'ENTIDADNACIMIENTO'] = 'Baja California Sur'
df.loc[df['ENTIDADNACIMIENTO'] == '4', 'ENTIDADNACIMIENTO'] = 'Campeche'
df.loc[df['ENTIDADNACIMIENTO'] == '5', 'ENTIDADNACIMIENTO'] = 'Coahuila'
df.loc[df['ENTIDADNACIMIENTO'] == '6', 'ENTIDADNACIMIENTO'] = 'Colima'
df.loc[df['ENTIDADNACIMIENTO'] == '7', 'ENTIDADNACIMIENTO'] = 'Chiapas'
df.loc[df['ENTIDADNACIMIENTO'] == '8', 'ENTIDADNACIMIENTO'] = 'Chihuahua'
df.loc[df['ENTIDADNACIMIENTO'] == '9', 'ENTIDADNACIMIENTO'] = 'Ciudad de México'
df.loc[df['ENTIDADNACIMIENTO'] == '10', 'ENTIDADNACIMIENTO'] = 'Durango'
df.loc[df['ENTIDADNACIMIENTO'] == '11', 'ENTIDADNACIMIENTO'] = 'Guanajuato'
df.loc[df['ENTIDADNACIMIENTO'] == '12', 'ENTIDADNACIMIENTO'] = 'Guerrero'
df.loc[df['ENTIDADNACIMIENTO'] == '13', 'ENTIDADNACIMIENTO'] = 'Hidalgo'
df.loc[df['ENTIDADNACIMIENTO'] == '14', 'ENTIDADNACIMIENTO'] = 'Jalisco'
df.loc[df['ENTIDADNACIMIENTO'] == '15', 'ENTIDADNACIMIENTO'] = 'México'
df.loc[df['ENTIDADNACIMIENTO'] == '16', 'ENTIDADNACIMIENTO'] = 'Michoacán'
df.loc[df['ENTIDADNACIMIENTO'] == '17', 'ENTIDADNACIMIENTO'] = 'Morelos'
df.loc[df['ENTIDADNACIMIENTO'] == '18', 'ENTIDADNACIMIENTO'] = 'Nayarit'
df.loc[df['ENTIDADNACIMIENTO'] == '19', 'ENTIDADNACIMIENTO'] = 'Nuevo León'
df.loc[df['ENTIDADNACIMIENTO'] == '20', 'ENTIDADNACIMIENTO'] = 'Oaxaca'
df.loc[df['ENTIDADNACIMIENTO'] == '21', 'ENTIDADNACIMIENTO'] = 'Puebla'
df.loc[df['ENTIDADNACIMIENTO'] == '22', 'ENTIDADNACIMIENTO'] = 'Querétaro'
df.loc[df['ENTIDADNACIMIENTO'] == '23', 'ENTIDADNACIMIENTO'] = 'Quintana Roo'
df.loc[df['ENTIDADNACIMIENTO'] == '24', 'ENTIDADNACIMIENTO'] = 'San Luis Potosí'
df.loc[df['ENTIDADNACIMIENTO'] == '25', 'ENTIDADNACIMIENTO'] = 'Sinaloa'
df.loc[df['ENTIDADNACIMIENTO'] == '26', 'ENTIDADNACIMIENTO'] = 'Sonora'
df.loc[df['ENTIDADNACIMIENTO'] == '27', 'ENTIDADNACIMIENTO'] = 'Tabasco'
df.loc[df['ENTIDADNACIMIENTO'] == '28', 'ENTIDADNACIMIENTO'] = 'Tamaulipas'
df.loc[df['ENTIDADNACIMIENTO'] == '29', 'ENTIDADNACIMIENTO'] = 'Tlaxcala'
df.loc[df['ENTIDADNACIMIENTO'] == '30', 'ENTIDADNACIMIENTO'] = 'Veracruz'
df.loc[df['ENTIDADNACIMIENTO'] == '31', 'ENTIDADNACIMIENTO'] = 'Yucatán'
df.loc[df['ENTIDADNACIMIENTO'] == '32', 'ENTIDADNACIMIENTO'] = 'Zacatecas'

df

,NACIOEXTRANJERO,ENTIDADNACIMIENTO,MUNICIPIONACIMIENTO,EDAD,SECONSIDERAINDIGENA,HABLALENGUAINDIGENA,FECHANACIMIENTOMADRE,ESTADOCONYUGAL,RESIDEEXTRANJERO,ENTIDADRESIDENCIA,...,TIPOMEDICOATENDIO,ENTIDADFEDERATIVAPARTO,MUNICIPIOPARTO,LOCALIDADPARTO,CERTIFICADOPOR,CLUESCERTIFICA,ENTIDADFEDERATIVACERTIFICA,MUNICIPIOCERTIFICA,LOCALIDADCERTIFICA,FECHACERTIFICADO
756895,2,Aguascalientes,1,23,2,2,23/03/2000,5,2,1,...,11.0,1,1,1,1,ASIMS000016,1,1,1,23/07/2023
713039,2,Aguascalientes,2,38,2,2,19/01/1985,5,2,1,...,11.0,1,6,1,1,ASSSA000614,1,6,1,10/04/2023
713036,2,Aguascalientes,1,27,2,2,23/05/1995,5,2,1,...,11.0,1,1,1,1,ASSMP000115,1,1,1,16/04/2023
713032,2,Aguascalientes,1,28,2,2,28/08/1994,5,2,1,...,11.0,1,1,1,1,ASSMP000103,1,1,1,26/03/2023
713047,2,Aguascalientes,1,16,2,2,23/07/2006,4,2,1,...,13.0,1,1,1,1,ASSSA000042,1,1,1,30/01/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697039,2,Zacatecas,17,25,2,2,10/09/1997,4,2,32,...,11.0,32,17,1,2,ZSSSA012450,32,17,1,02/02/2023
66130,2,Zacatecas,17,33,2,2,25/04/1989,5,2,8,...,13.0,8,37,1,1,NaN,8,37,1,24/01/2023
697001,2,Zacatecas,17,29,2,2,03/09/1993,5,2,32,...,13.0,32,17,1,2,ZSSSA012450,32,17,1,09/01/2023
697149,2,Zacatecas,17,14,2,2,22/04/2008,4,2,32,...,11.0,32,17,1,2,ZSSSA012450,32,17,1,16/02/2023
172472,2,Zacatecas,10,21,2,2,30/08/2001,5,2,32,...,11.0,32,10,1,1,NaN,32,10,1,07/03/2023

Ya hemos renombrado cada estado adecuadamente, ahora trabajemos con esta base.

In [64]:
# Filtremos los datos por estado. Para nuestro ejemplo, utilizamos Sonora

df_sonora = df[df.ENTIDADNACIMIENTO == 'Sonora']
df_sonora

,NACIOEXTRANJERO,ENTIDADNACIMIENTO,MUNICIPIONACIMIENTO,EDAD,SECONSIDERAINDIGENA,HABLALENGUAINDIGENA,FECHANACIMIENTOMADRE,ESTADOCONYUGAL,RESIDEEXTRANJERO,ENTIDADRESIDENCIA,...,TIPOMEDICOATENDIO,ENTIDADFEDERATIVAPARTO,MUNICIPIOPARTO,LOCALIDADPARTO,CERTIFICADOPOR,CLUESCERTIFICA,ENTIDADFEDERATIVACERTIFICA,MUNICIPIOCERTIFICA,LOCALIDADCERTIFICA,FECHACERTIFICADO
953391,2,Sonora,29,42,2,2,20/02/1981,1,2,26,...,11.0,26,30,1,7,SRSSA001105,26,30,1,23/05/2023
308631,2,Sonora,42,32,1,2,11/12/1990,4,2,26,...,11.0,26,42,1,2,NaN,26,42,1,08/05/2023
308635,2,Sonora,33,43,2,2,14/01/1980,5,2,26,...,11.0,26,18,1,1,NaN,26,18,1,11/05/2023
769624,2,Sonora,30,26,2,2,18/02/1997,4,2,26,...,11.0,26,30,1,7,SRSSA001105,26,30,1,14/08/2023
240718,2,Sonora,30,25,2,2,15/03/1998,4,2,26,...,11.0,26,43,104,1,NaN,26,43,104,31/03/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66342,2,Sonora,18,23,2,2,09/01/2000,4,2,26,...,11.0,26,18,1,1,NaN,26,18,1,25/01/2023
722784,2,Sonora,30,25,2,2,18/11/1997,1,2,26,...,11.0,26,30,1,7,SRSSA001105,26,30,1,05/05/2023
723483,2,Sonora,30,24,2,2,01/05/1999,5,2,25,...,11.0,25,11,1,1,SLIMS000271,25,11,1,27/07/2023
722822,2,Sonora,30,16,2,2,22/03/2007,1,2,26,...,11.0,26,30,1,7,SRSSA001105,26,30,1,29/10/2023
213112,2,Sonora,33,27,2,2,16/12/1995,4,2,26,...,11.0,26,30,1,1,NaN,26,30,1,30/03/2023

In [70]:
# Contemos los municipios

df_sonora.MUNICIPIONACIMIENTO.value_counts()

MUNICIPIONACIMIENTO
30    8749
18    5994
42    3034
43    2087
29    2016
      ...
34       1
9        1
46       1
54       1
24       1
Name: count, Length: 72, dtype: int64

Qué alegria, nuestros resultados coinciden con la realidad, Sonora sí tiene 72 municipios. ¿Será prudente renombrarlos?

In [71]:
df_sonora = df_sonora.sort_values(by=['MUNICIPIONACIMIENTO'])
df_sonora

,NACIOEXTRANJERO,ENTIDADNACIMIENTO,MUNICIPIONACIMIENTO,EDAD,SECONSIDERAINDIGENA,HABLALENGUAINDIGENA,FECHANACIMIENTOMADRE,ESTADOCONYUGAL,RESIDEEXTRANJERO,ENTIDADRESIDENCIA,...,TIPOMEDICOATENDIO,ENTIDADFEDERATIVAPARTO,MUNICIPIOPARTO,LOCALIDADPARTO,CERTIFICADOPOR,CLUESCERTIFICA,ENTIDADFEDERATIVACERTIFICA,MUNICIPIOCERTIFICA,LOCALIDADCERTIFICA,FECHACERTIFICADO
463704,2,Sonora,1,24,2,2,10/03/1999,5,2,26,...,11.0,26,66,1,7,NaN,26,66,1,15/07/2023
439006,2,Sonora,1,21,9,9,23/08/2001,4,2,26,...,16.0,26,55,1,4,NaN,26,55,1,04/07/2023
351936,2,Sonora,1,14,2,2,23/02/2009,4,2,6,...,11.0,6,9,1,1,NaN,6,9,1,07/05/2023
1330558,2,Sonora,1,26,2,2,21/05/1996,1,2,26,...,11.0,26,30,1,7,SRSSA001105,26,30,1,17/02/2023
411112,2,Sonora,1,15,2,2,27/12/2007,1,2,26,...,11.0,26,41,1,2,NaN,26,41,1,13/07/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253495,2,Sonora,999,32,2,2,06/03/1991,4,2,2,...,11.0,2,4,1,1,NaN,2,4,1,11/04/2023
934724,2,Sonora,999,21,2,2,31/01/2002,4,2,19,...,11.0,19,39,1,7,NLIMS000320,19,39,1,29/04/2023
592805,2,Sonora,999,24,2,2,25/01/1999,1,2,11,...,NaN,11,18,1,2,GTSMP000943,11,18,1,13/10/2023
22862,2,Sonora,999,25,2,2,28/11/1997,4,2,26,...,11.0,26,42,1,7,NaN,26,42,1,04/01/2023
21569,2,Sonora,999,35,2,2,15/03/1987,1,2,11,...,11.0,11,37,1,1,NaN,11,37,1,04/01/2023

In [82]:
# Herramientas para renombrar

numeros = {'col1': list(range(1, 73))}
df = pd.DataFrame(numeros)

municipios = ['Aconchi', 'Agua Prieta', 'Alamos', 'Altar', 'Arivechi', 'Arizpe', 'Atil', 'Bacadéhuachi', 'Bacanora', 'Bacerac', 'Bacoachi', 'Bácum', 'Banámichi', 'Baviácora', 'Bavispe', 'Benjamín Hill', 'Caborca', 'Cajeme', 'Cananea', 'Carbó', 'La Colorada', 'Cucurpe', 'Cumpas', 'Divisaderos', 'Empalme', 'Etchojoa', 'Fronteras', 'Granados', 'Guaymas', 'Hermosillo', 'Huachinera', 'Huásabas', 'Huatabampo', 'Huépac', 'Imuris', 'Magdalena', 'Mazatán', 'Moctezuma', 'Naco', 'Nácori Chico', 'Nacozari de García', 'Navojoa', 'Nogales', 'Ónavas', 'Opodepe', 'Oquitoa', 'Pitiquito', 'Puerto Peñasco', 'Quiriego', 'Rayón496', 'Rosario', 'Sahuaripa', 'San Felipe de Jesús', 'San Javier', 'San Luis Río Colorado', 'San Miguel de Horcasitas', 'San Pedro de la Cueva', 'Santa Ana', 'Santa Cruz', 'Sáric', 'Soyopa', 'Suaqui Grande', 'Tepache', 'Trincheras', 'Tubutama', 'Ures', 'Villa Hidalgo', 'Villa Pesqueira', 'Yécora', 'General Plutarco Elías Calles', 'Benito Juárez', 'San Ignacio Río Muerto']

In [83]:
# Renombramiento en masa

mapping = {i: municipios[i-1] for i in range(1, 73)}

In [84]:
df_sonora['MUNICIPIONACIMIENTO'] = df_sonora['MUNICIPIONACIMIENTO'].replace(mapping)
df_sonora

,NACIOEXTRANJERO,ENTIDADNACIMIENTO,MUNICIPIONACIMIENTO,EDAD,SECONSIDERAINDIGENA,HABLALENGUAINDIGENA,FECHANACIMIENTOMADRE,ESTADOCONYUGAL,RESIDEEXTRANJERO,ENTIDADRESIDENCIA,...,TIPOMEDICOATENDIO,ENTIDADFEDERATIVAPARTO,MUNICIPIOPARTO,LOCALIDADPARTO,CERTIFICADOPOR,CLUESCERTIFICA,ENTIDADFEDERATIVACERTIFICA,MUNICIPIOCERTIFICA,LOCALIDADCERTIFICA,FECHACERTIFICADO
463704,2,Sonora,Aconchi,24,2,2,10/03/1999,5,2,26,...,11.0,26,66,1,7,NaN,26,66,1,15/07/2023
439006,2,Sonora,Aconchi,21,9,9,23/08/2001,4,2,26,...,16.0,26,55,1,4,NaN,26,55,1,04/07/2023
351936,2,Sonora,Aconchi,14,2,2,23/02/2009,4,2,6,...,11.0,6,9,1,1,NaN,6,9,1,07/05/2023
1330558,2,Sonora,Aconchi,26,2,2,21/05/1996,1,2,26,...,11.0,26,30,1,7,SRSSA001105,26,30,1,17/02/2023
411112,2,Sonora,Aconchi,15,2,2,27/12/2007,1,2,26,...,11.0,26,41,1,2,NaN,26,41,1,13/07/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253495,2,Sonora,999,32,2,2,06/03/1991,4,2,2,...,11.0,2,4,1,1,NaN,2,4,1,11/04/2023
934724,2,Sonora,999,21,2,2,31/01/2002,4,2,19,...,11.0,19,39,1,7,NLIMS000320,19,39,1,29/04/2023
592805,2,Sonora,999,24,2,2,25/01/1999,1,2,11,...,NaN,11,18,1,2,GTSMP000943,11,18,1,13/10/2023
22862,2,Sonora,999,25,2,2,28/11/1997,4,2,26,...,11.0,26,42,1,7,NaN,26,42,1,04/01/2023
21569,2,Sonora,999,35,2,2,15/03/1987,1,2,11,...,11.0,11,37,1,1,NaN,11,37,1,04/01/2023

In [87]:
df_sonora.MUNICIPIONACIMIENTO.value_counts()

MUNICIPIONACIMIENTO
Hermosillo     8749
Cajeme         5994
Navojoa        3034
Nogales        2087
Guaymas        2016
               ...
Huépac            1
Bacanora          1
Oquitoa           1
San Javier        1
Divisaderos       1
Name: count, Length: 72, dtype: int64

Ya está tomando sentido nuestra basaecita, la información que reemplazamos tiene sentido con la realidad. Veremos qué más podemos hacer.

¿Quien fue la mamá mayor del estado de Sonora en el año 2023?

In [98]:
# Transformamos la fecha de object a date:

df_sonora['FECHANACIMIENTOMADRE'] = pd.to_datetime(df_sonora['FECHANACIMIENTOMADRE'], format='%d/%m/%Y')

In [107]:
edad_maxima = df_sonora.loc[df_sonora.FECHANACIMIENTOMADRE.idxmin()]
edad_maxima[['FECHANACIMIENTOMADRE', 'FECHANACIMIENTO', 'FECHACERTIFICADO']]

FECHANACIMIENTOMADRE    1970-02-07 00:00:00
FECHACERTIFICADO                 21/07/2023
Name: 425486, dtype: object

¿Podremos hallar a la menor?

In [108]:
edad_minima = df_sonora.loc[df_sonora.FECHANACIMIENTOMADRE.idxmax()]
edad_minima[['FECHANACIMIENTOMADRE', 'FECHANACIMIENTO', 'FECHACERTIFICADO']]

FECHANACIMIENTOMADRE    2011-09-08 00:00:00
FECHANACIMIENTO                  24/08/2023
FECHACERTIFICADO                 25/08/2023
Name: 790320, dtype: object

¡En la torre! Hemos hallado que la madre más joven de Sonora tiene solo... ¿12 AÑOS? ¿Habremos descubierto un crimen aquí? Veamos dónde ocurrió.

In [113]:
# Habrá algo aquí que nos sirva?

print(df_sonora.columns)

Index(['NACIOEXTRANJERO', 'ENTIDADNACIMIENTO', 'MUNICIPIONACIMIENTO', 'EDAD',
       'SECONSIDERAINDIGENA', 'HABLALENGUAINDIGENA', 'FECHANACIMIENTOMADRE',
       'ESTADOCONYUGAL', 'RESIDEEXTRANJERO', 'ENTIDADRESIDENCIA',
       'MUNICIPIORESIDENCIA', 'LOCALIDADRESIDENCIA', 'NUMEROEMBARAZOS',
       'HIJOSNACIDOSMUERTOS', 'HIJOSNACIDOSVIVOS', 'HIJOSSOBREVIVIENTES',
       'CONDICIONHIJOANTERIOR', 'VIVEHIJOANTERIOR', 'ORDENNACIMIENTO',
       'ATENCIONPRENATAL', 'TRIMESTREPRIMERCONSULTA', 'TOTALCONSULTAS',
       'SOBREVIVIOPARTO', 'AFILIACION', 'ESCOLARIDAD', 'INTERRUMPIOESTUDIOS',
       'CLAVEOCUPACIONHABITUAL', 'TRABAJAACTUALMENTE', 'EDADPADRE',
       'FECHANACIMIENTO', 'HORANACIMIENTO', 'SEXO', 'EDADGESTACIONAL', 'TALLA',
       'PESO', 'APGAR', 'SILVERMAN', 'TAMIZAUDITIVO', 'VACUNA_BCG',
       'VACUNAHEPATITIS_B', 'VITAMINA_A', 'VITAMINA_K', 'PRODUCTOEMBARAZO',
       'ORDENPRODUCTO', 'TOTALPRODUCTOS', 'CODIGOCIEANOMALIA1',
       'CODIGOCIEANOMALIA2', 'LUGARNACIMIENTO', 'CLUES', 'TIEMPOTRASLADO',
       'RESOLUCIONEMBARAZO', 'UTILIZOFORCEPS', 'TIPOCESAREA',
       'PERSONALATENDIO', 'TIPOMEDICOATENDIO', 'ENTIDADFEDERATIVAPARTO',
       'MUNICIPIOPARTO', 'LOCALIDADPARTO', 'CERTIFICADOPOR', 'CLUESCERTIFICA',
       'ENTIDADFEDERATIVACERTIFICA', 'MUNICIPIOCERTIFICA',
       'LOCALIDADCERTIFICA', 'FECHACERTIFICADO'],
      dtype='object')

In [115]:
edad_minima[['HIJOSNACIDOSVIVOS', 'SOBREVIVIOPARTO', 'ESCOLARIDAD', 'PERSONALATENDIO']]

HIJOSNACIDOSVIVOS     1
SOBREVIVIOPARTO       1
ESCOLARIDAD          32
PERSONALATENDIO       1
Name: 790320, dtype: object

Vemos aquí que tanto la madre como el bebé sobrevivieron al parto. Tenemos información suficiente para iniciar una investigación...